# Generated by Django 4.0.5 on 2022-07-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_address_person_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
